### ISSUE TITLE
getting this issue after running "notflix moviename"

### ISSUE THREAD

**Issue by ihasidul** [Bugswriter/notflix#60]
/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:2
import chalk from 'chalk'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
   ~ 

**Comment by AryaKesharwani** [comment]
install this as global dependency  https://www.npmjs.com/package/peerflix 
it ran fine for me 
i don't have webtorrent-cli installed

**Comment by misobarisic** [comment]
This is not a notflix related issue.

Your npm dependency was not installed correctly. Make sure to try reinstalling `webtorrent-cli` with `npm i -g webtorrent-cli`. This may require root permissions.

**Comment by BobIsMyManager** [comment]
You need to update notflix by running `sudo curl -sL "https://raw.githubusercontent.com/Bugswriter/notflix/master/notflix" -o /usr/local/bin/notflix` and install peerflix by running `sudo npm install peerflix -g`

**Comment by misobarisic** [comment]
> You need to update notflix by running `sudo curl -sL "https://raw.githubusercontent.com/Bugswriter/notflix/master/notflix" -o /usr/local/bin/notflix` and install peerflix by running `sudo npm install peerflix -g`

There have been new commits to the main branch but the problem specified here isn't going to be solved inherently by updating to a newer version of the script.

**Comment by ihasidul** [comment]
After upgrading to the new version of the script and upgrading peerflix it is working fine for me.
